config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/' =>'posts#top'
  get '/posts/:id' => 'posts#show', as: 'show_post'
  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'
  patch '/posts/:id' => 'posts#update', as: 'update_post'
  delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def top
  end

  def index
    @posts = Post.all
    @post = Post.new
  end

  def create
    @posts = Post.all
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Book was successfully created."
      redirect_to show_post_path(@post.id)
    else
      render 'index'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to show_post_path(@post.id)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Book was successfully destroyed."
      redirect_to posts_path
    else
      render 'index'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>

    <%= yield %>

  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing Book</h1>
  <%= form_for(@post) do |f| %>

	 <% if @post.errors.any? %>
  		<div id="error_explanation" class="alert alert-danger">
   		 	<ul>
      		<% @post.errors.full_messages.each do |message| %>
        	<li><%= message %></li>
      		<% end %>
    		</ul>
    		</div>
	 <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: "book_title"%>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, class: "book_body"%>
  </div>

  <div class="actions">
    <%= f.submit 'Update Book' %>
  </div>
    <% end %>

  <% id = @post.id %>
  <%= link_to "Show", post_path(@post.id), class: "show_#{id}"  %> |
  <%= link_to "Back", posts_path, class: "back"%>

app/views/posts/index.html.erb
<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
          <% id = post.id %>
      <td><%= link_to "Show", show_post_path(post.id), class: "show_#{id}" %>
          <%= link_to "Edit", edit_post_path(post.id), class: "edit_#{id}" %>
          <%= link_to "Destroy", destroy_post_path(post.id), class: "destroy_#{id}", method: :delete, "data-confirm" => "Are you sure?" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<h2>New book</h2>
<%= form_for(@post) do |f| %>

  <% if @post.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title, class: "book_title" %>
</div>

<div class="field">
  <%= f.label :body %>
  <%= f.text_area :body, class: "book_body" %>
</div>

<div class="actions">
  <%= f.submit 'Create Book' %>
</div>
<% end %>

app/views/posts/show.html.erb
<p><strong>Title : </strong><%= @post.title %></p>
<p><strong>Body : </strong><%= @post.body %></p>
<% id = @post.id %>
<%= link_to "Edit", edit_post_path(@post.id), class: "edit_#{id}" %> |
<%= link_to "Back", posts_path, class: "back"%>

app/views/posts/top.html.erb
<h1>ようこそ <strong>Bookers</strong>  へ！</h1>
<p><strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><a href="/posts">start</a></p>